### ISSUE TITLE
In reference with: author-Sanchay Joshi(1).c

### ISSUE THREAD

**Issue by IkshulDureja** [ISTE-TIET/Code-Debugging#12]
![image](https://user-images.githubusercontent.com/56119070/102264530-cd01ce00-3f3b-11eb-9302-8d0434479d71.png)

**Comment by yuvisidhu19** [comment]
![debug](https://user-images.githubusercontent.com/67970877/102512230-cc8a4400-40af-11eb-83dc-a63ef61d8e28.JPG)
It's working fine for me.
